<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit401a611a637bc7f9db7b4d284da4ff92
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'FuseSource' => 
            array (
                0 => __DIR__ . '/..' . '/fusesource/stomp-php/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit401a611a637bc7f9db7b4d284da4ff92::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit401a611a637bc7f9db7b4d284da4ff92::$classMap;

        }, null, ClassLoader::class);
    }
}
